import { Airport } from "../interface/airports.interface";

export const AIRPORTS: Airport[] = [
  { id: 1,  iataCode: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai',        country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 2,  iataCode: 'DEL', name: 'Indira Gandhi International Airport',                 city: 'New Delhi',     country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 3,  iataCode: 'BLR', name: 'Kempegowda International Airport',                    city: 'Bengaluru',     country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 4,  iataCode: 'HYD', name: 'Rajiv Gandhi International Airport',                  city: 'Hyderabad',     country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 5,  iataCode: 'MAA', name: 'Chennai International Airport',                       city: 'Chennai',       country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 6,  iataCode: 'CCU', name: 'Netaji Subhas Chandra Bose International Airport',    city: 'Kolkata',       country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 7,  iataCode: 'PNQ', name: 'Pune Airport',                                       city: 'Pune',          country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 8,  iataCode: 'GOI', name: 'Dabolim Airport',                                    city: 'Goa',           country: 'India',              countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { id: 9,  iataCode: 'DXB', name: 'Dubai International Airport',                         city: 'Dubai',         country: 'United Arab Emirates', countryCode: 'AE', timezone: 'Asia/Dubai' },
  { id: 10, iataCode: 'AUH', name: 'Zayed International Airport',                         city: 'Abu Dhabi',     country: 'United Arab Emirates', countryCode: 'AE', timezone: 'Asia/Dubai' },
  { id: 11, iataCode: 'DOH', name: 'Hamad International Airport',                         city: 'Doha',          country: 'Qatar',              countryCode: 'QA', timezone: 'Asia/Qatar' },
  { id: 12, iataCode: 'SIN', name: 'Singapore Changi Airport',                           city: 'Singapore',     country: 'Singapore',          countryCode: 'SG', timezone: 'Asia/Singapore' },
  { id: 13, iataCode: 'KUL', name: 'Kuala Lumpur International Airport',                  city: 'Kuala Lumpur',  country: 'Malaysia',           countryCode: 'MY', timezone: 'Asia/Kuala_Lumpur' },
  { id: 14, iataCode: 'BKK', name: 'Suvarnabhumi Airport',                               city: 'Bangkok',       country: 'Thailand',           countryCode: 'TH', timezone: 'Asia/Bangkok' },
  { id: 15, iataCode: 'HKG', name: 'Hong Kong International Airport',                     city: 'Hong Kong',     country: 'Hong Kong',          countryCode: 'HK', timezone: 'Asia/Hong_Kong' },
  { id: 16, iataCode: 'LHR', name: 'Heathrow Airport',                                   city: 'London',        country: 'United Kingdom',     countryCode: 'GB', timezone: 'Europe/London' },
  { id: 17, iataCode: 'CDG', name: 'Charles de Gaulle Airport',                          city: 'Paris',         country: 'France',             countryCode: 'FR', timezone: 'Europe/Paris' },
  { id: 18, iataCode: 'FRA', name: 'Frankfurt Airport',                                  city: 'Frankfurt',     country: 'Germany',            countryCode: 'DE', timezone: 'Europe/Berlin' },
  { id: 19, iataCode: 'AMS', name: 'Amsterdam Airport Schiphol',                         city: 'Amsterdam',     country: 'Netherlands',        countryCode: 'NL', timezone: 'Europe/Amsterdam' },
  { id: 20, iataCode: 'IST', name: 'Istanbul Airport',                                   city: 'Istanbul',      country: 'Türkiye',            countryCode: 'TR', timezone: 'Europe/Istanbul' },
  { id: 21, iataCode: 'JFK', name: 'John F. Kennedy International Airport',               city: 'New York',      country: 'United States',      countryCode: 'US', timezone: 'America/New_York' },
  { id: 22, iataCode: 'EWR', name: 'Newark Liberty International Airport',                city: 'Newark',        country: 'United States',      countryCode: 'US', timezone: 'America/New_York' },
  { id: 23, iataCode: 'LAX', name: 'Los Angeles International Airport',                   city: 'Los Angeles',   country: 'United States',      countryCode: 'US', timezone: 'America/Los_Angeles' },
  { id: 24, iataCode: 'SFO', name: 'San Francisco International Airport',                 city: 'San Francisco', country: 'United States',      countryCode: 'US', timezone: 'America/Los_Angeles' },
  { id: 25, iataCode: 'ORD', name: "O'Hare International Airport",                        city: 'Chicago',       country: 'United States',      countryCode: 'US', timezone: 'America/Chicago' },
  { id: 26, iataCode: 'YYZ', name: 'Toronto Pearson International Airport',               city: 'Toronto',       country: 'Canada',             countryCode: 'CA', timezone: 'America/Toronto' },
  { id: 27, iataCode: 'SYD', name: 'Sydney Kingsford Smith Airport',                     city: 'Sydney',        country: 'Australia',          countryCode: 'AU', timezone: 'Australia/Sydney' },
  { id: 28, iataCode: 'MEL', name: 'Melbourne Airport',                                  city: 'Melbourne',     country: 'Australia',          countryCode: 'AU', timezone: 'Australia/Melbourne' },
  { id: 29, iataCode: 'NRT', name: 'Narita International Airport',                        city: 'Tokyo',         country: 'Japan',              countryCode: 'JP', timezone: 'Asia/Tokyo' },
  { id: 30, iataCode: 'ICN', name: 'Incheon International Airport',                       city: 'Seoul',         country: 'South Korea',        countryCode: 'KR', timezone: 'Asia/Seoul' },
];